name: native-binary-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  native-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'graalvm'
          cache: maven

      - name: Build JAR with Maven (on host)
        run: mvn clean package -DskipTests

      - name: Build native binary using GraalVM in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/graalvm/native-image-community:24-muslib-ol8  \
              --no-fallback \
              --static \
              --libc=musl \
              -cp target/mgrep-1.0-SNAPSHOT.jar \
              cn.wangfeixiong.mgrep.MGrepApp
          
      - name: Show binary size
        run: ls -lh ./mgrep

      - name: Upload native binary
        uses: actions/upload-artifact@v4
        with:
          name: native-image
          path: ./mgrep
