name: Build Native Image with GraalVM 21

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up GraalVM 21
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Install native build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libz-dev zlib1g-dev
      
      - name: Build with Maven
        run: mvn -B clean package -Pnative -DskipTests
      
      - name: Upload native image
        uses: actions/upload-artifact@v4
        with:
          name: native-image
          path: target/*-runner    
